extends:
  - eslint:recommended
  - plugin:prettier/recommended
parser:
 babel-eslint
env:
 browser: true
 es6: true
overrides:
  - 
    files:
      - "**/*.ts"
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:prettier/recommended
      - prettier/@typescript-eslint
    parser: '@typescript-eslint/parser'
  - 
    files:
      - '*.config.js'
    env:
      browser: false
      node: true
  - 
    files:
      - tests/**/*.js
    env:
      jest: true
      node : true
    plugins:
     - jest
    extends:
      - plugin:jest/recommended
