export default [
  {
    state: 'open',
    projectPath: 'gitlab-org/gitlab',
    reference: '#11111',
    iid: '11111',
    webUrl: 'https://gitlab.com/gitlab-org/gitlab/-/issues/22222',
    title: 'Test issue 11111',
    projectId: '2',
    fullReference: 'gitlab-org/gitlab#11111',
  },
  {
    state: 'open',
    projectPath: 'gitlab-org/gitlab',
    reference: '#22222',
    iid: '22222',
    webUrl: 'https://gitlab.com/gitlab-org/gitlab/-/issues/22222',
    title: 'Test issue 22222',
    projectId: '2',
    fullReference: 'gitlab-org/gitlab#22222',
  },
  {
    state: 'open',
    projectPath: 'gitlab-org/gitlab',
    reference: '#33333',
    iid: '33333',
    webUrl: 'https://gitlab.com/gitlab-org/gitlab/-/issues/33333',
    title: 'Test issue 33333',
    projectId: '2',
    fullReference: 'gitlab-org/gitlab#33333',
  },
  {
    state: 'open',
    projectPath: 'gitlab-org/gitlab-test',
    reference: '#22222',
    iid: '22222',
    webUrl: 'https://gitlab.com/gitlab-org/gitlab/-/issues/22222',
    title: 'Test issue 22222',
    projectId: '1',
    fullReference: 'gitlab-org/gitlab-test#22222',
  },
];
